namespace: gluster
name: gluster
version: 1.0.1
readme: README.md
authors:
  - gluster (github.com/gluster)```
  - Prajith Kesava Prasad <pkesavap@redhat.com>
  - Kesavan Vellalore Thiruvenkadasamy <kvellalo@redhat.com>

description: Administrate a gluster cluster.
license_file: ./LICENSE
tags: [gluster, storage]
dependencies: {}
repository: https://github.com/gluster/gluster-ansible-collection
documentation: https://docs.ansible.com/ansible/latest/
homepage: https://github.com/gluster/gluster-ansible-collection
issues: https://github.com/gluster/gluster-ansible-collection/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
