namespace: gluster
name: gluster
version: 1.0.0
readme: README.md

# A list of the collection's content authors. Can be just the name or in the format 'Full Name <email> (url)
# @nicks:irc/im.site#channel'
authors:
  - gluster (github.com/gluster)```

description: Administrate a gluster cluster.
license:
- GPL-2.0-or-later
tags: [gluster, storage]
dependencies: {}
repository: https://github.com/gluster/gluster-ansible-collection
documentation: https://docs.ansible.com/ansible/latest/
homepage: https://github.com/gluster/gluster-ansible-collection
issues: https://github.com/gluster/gluster-ansible-collection/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
