namespace: gluster
name: gluster
version: 1.0.0
readme: README.md

# A list of the collection's content authors. Can be just the name or in the format 'Full Name <email> (url)
# @nicks:irc/im.site#channel'
authors:
- your name <example@domain.com>

description: This collection provides modules to administrate a gluster cluster.
license:
- GPL-2.0-or-later
tags: [gluster, storage]
dependencies: {}
repository: https://github.com/gluster/gluster-ansible-collection
documentation: https://docs.ansible.com/ansible/latest/
homepage: https://github.com/gluster/gluster-ansible-collection
issues: https://github.com/gluster/gluster-ansible-collection/issues
